// <auto-generated />
using System;
using CleveCoding.Permissions.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleveCoding.Permissions.Migrations
{
    [DbContext(typeof(PermissionDbContext))]
    partial class PermissionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CleveCoding.Permissions.Entities.UserPermissionAuditEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<short>("Action")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("OldValue")
                        .HasColumnType("bit");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPermissionAudits", (string)null);
                });

            modelBuilder.Entity("CleveCoding.Permissions.Entities.UserPermissionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Action")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HasAccess")
                        .HasColumnType("bit");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("varchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserPermissions", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
